# Generated by Django 4.2.4 on 2023-08-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='icone',
            field=models.ImageField(upload_to='Icone', verbose_name='Icone do Banco'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='valor',
            field=models.FloatField(verbose_name='Valor do deposito'),
        ),
    ]
